services:
  mariadb:
    build:
      context: requirements/mariadb
    image: mariadb
    container_name: mariadb
    environment:
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_ADMIN: ${ADMINER_USER}
      DB_ADMIN_PASSWORD: ${ADMINER_PASSWORD}
      DB_ADMIN_CLIENT: adminer.inception
      DB_CLIENT: wordpress.inception
      DB_NAME: ${WP_DB_NAME}
      DB_USER: ${WP_DB_USER}
      DB_PASSWORD: ${WP_DB_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "mariadb-admin ping --socket=/var/lib/mysql/sockets/mysqld.sock -u root -p$DB_ROOT_PASSWORD || mariadb-admin ping --socket=/var/lib/mysql/sockets/mysqld.sock -u root"]
      interval: 2s
      timeout: 5s
      retries: 30
    networks:
      - backend

  wordpress:
    build:
      context: requirements/wordpress
    image: wordpress
    container_name: wordpress
    hostname: wordpress
    environment:
    # Set host UID/GID to match host user for proper file permissions
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
    # DB settings
      DB_HOST: mariadb
      DB_NAME: ${WP_DB_NAME}
      DB_USER: ${WP_DB_USER}
      DB_PASSWORD: ${WP_DB_PASSWORD}
    # Redis settings
      REDIS_HOST: redis
      REDIS_PORT: 6379
    # User & Site settings
      ADMIN_USER: ${WP_ADMIN_USER}
      ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      NON_ADMIN_USER: ${WP_NON_ADMIN_USER}
      NON_ADMIN_PASSWORD: ${WP_NON_ADMIN_PASSWORD}
      SITE_URL: https://${DOMAIN_NAME}
      SITE_TITLE: ${WP_SITE_TITLE}
    # Security keys
      AUTH_KEY: ${WP_AUTH_KEY}
      SECURE_AUTH_KEY: ${WP_SECURE_AUTH_KEY}
      LOGGED_IN_KEY: ${WP_LOGGED_IN_KEY}
      NONCE_KEY: ${WP_NONCE_KEY}
      AUTH_SALT: ${WP_AUTH_SALT}
      SECURE_AUTH_SALT: ${WP_SECURE_AUTH_SALT}
      LOGGED_IN_SALT: ${WP_LOGGED_IN_SALT}
      NONCE_SALT: ${WP_NONCE_SALT}
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "9000"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      backend:
        aliases:
          - wordpress

  nginx:
    build:
      context: requirements/nginx
    image: nginx
    container_name: nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped
    networks:
      backend:
        aliases:
          - ${DOMAIN_NAME}

  redis:
    image: redis
    build:
      context: requirements/bonus/redis
    container_name: redis
    restart: unless-stopped
    networks:
      - backend

  ftp:
    build:
      context: requirements/bonus/ftp
    image: ftp
    container_name: ftp
    environment:
      HOST_UID: ${HOST_UID}
      HOST_GID: ${HOST_GID}
      USERNAME: ${FTP_USER}
      PASSWORD: ${FTP_PASSWORD}
    ports:
      - "127.0.0.1:21:21"
      - "127.0.0.1:10000-10100:10000-10100"
    volumes:
      - wordpress:/home/${FTP_USER}
    restart: unless-stopped

  docs:
    build:
      context: requirements/bonus/docs
    image: docs
    container_name: docs
    restart: unless-stopped
    networks:
      - backend

  adminer:
    build:
      context: requirements/bonus/adminer
    image: adminer
    container_name: adminer
    restart: unless-stopped
    networks:
      backend:
        aliases:
          - adminer

  dozzle:
    build:
      context: requirements/bonus/dozzle
    image: dozzle
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
    - "127.0.0.1:80:8081"

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/wordpress

networks:
  backend:
    name: inception